apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubetelebot.fullname" . }}
rules:
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
- apiGroups: [""]
  resources:
  - pods
  - pods/log
  - deployments
  - services
  - namespaces
  - daemonset
  - statefulsets
  - persistentvolume
  - persistentvolumeclaim
  - replicasets
  - nodes
  - configmaps
  - endpoints
  verbs:
  - get
  - list
- apiGroups: [""]
  resources:
  - pods
  verbs:
  - get
  - list
  - delete
- apiGroups:
  - "networking.k8s.io"
  resources:
  - ingresses
  verbs:
  - get
  - list
