apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubetelebot.fullname" . }}
rules:
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
- apiGroups: [""]
  resources:
  - pods/log
  - secrets
  - services
  - namespaces
  - persistentvolumes
  - persistentvolumeclaims
  - nodes
  - configmaps
  - endpoints
  - serviceaccounts
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - statefulsets
  - daemonsets
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - patch
- apiGroups: [""]
  resources:
  - pods
  verbs:
  - get
  - list
  - delete
- apiGroups:
  - "networking.k8s.io"
  resources:
  - ingresses
  verbs:
  - get
  - list
