apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubetelebot.fullname" . }}
  labels:
    {{- include "kubetelebot.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kubetelebot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kubetelebot.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kubetelebot.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args:
          - ./kubetelebot
          - --apiKey
          - {{ .Values.apiKey }}
          - --allowedUser
          - {{ .Values.allowedUser }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
