name: publish-container
on:
  push:
    branches:
    - main

jobs:
  publish-app:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io/ashwinath
      GO_VERSION: 1.20.2
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install Go ${{ env.GO_VERSION }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Run tests
      run: make test
    - name: Setup GitHub Container Registry
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build and push
      run: make
